### ISSUE TITLE
can't connect to redis

### ISSUE THREAD

**Issue by xana-rahmani** [victorsteven/gophercon-jwt-repo#2]
I get this error:

"dial tcp 127.0.0.1:6379: connect: connection refused"

**Comment by victorsteven** [comment]
You can read up how to resolve that using: 
https://stackoverflow.com/questions/2333400/what-can-be-the-reasons-of-connection-refused-errors

**Comment by xana-rahmani** [comment]
> You can read up how to resolve that using:
> https://stackoverflow.com/questions/2333400/what-can-be-the-reasons-of-connection-refused-errors

Thanks
